version: '2'

services:
  osrm-quick:
    image: osrm
    ports: 
      - 5002:5000
    command: osrm latest quick.lua
  osrm-safe:
    image: osrm
    ports: 
      - 5004:5000
    command: osrm latest safe.lua
  osrm-scenic:
    image: osrm
    ports: 
      - 5006:5000
    command: osrm latest scenic.lua
  osrm-quiet:
    image: osrm
    ports: 
      - 5008:5000
    command: osrm latest quiet.lua